USE [BBDDPROYECTO]
GO
/****** Object:  Table [dbo].[RESTAURANTES]    Script Date: 02/04/2024 19:03:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RESTAURANTES](
	[IDRESTAURANTE] [int] NOT NULL,
	[NOMBRE] [nvarchar](100) NOT NULL,
	[CORREO] [nvarchar](100) NOT NULL,
	[TELEFONO] [nvarchar](9) NULL,
	[DIRECCION] [nvarchar](200) NOT NULL,
	[IMAGEN] [nvarchar](200) NOT NULL,
	[IDCATEGORIA] [int] NOT NULL,
 CONSTRAINT [PK_RESTAURANTES] PRIMARY KEY CLUSTERED 
(
	[IDRESTAURANTE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  View [dbo].[V_RESTAURANTES]    Script Date: 02/04/2024 19:03:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE   VIEW [dbo].[V_RESTAURANTES]
AS
	SELECT R.IDRESTAURANTE, R.NOMBRE, R.TELEFONO, R.CORREO,
	R.DIRECCION, R.IMAGEN, CR.NOMBRECATEGORIA,
	CAST(ISNULL(AVG(V.VALORACION), 0) AS DECIMAL(4,2)) AS VALORACION
	FROM RESTAURANTES R
	INNER JOIN CATEGORIAS_RESTAURANTES CR
	ON R.IDCATEGORIA = CR.IDCATEGORIA
	LEFT JOIN VALORACIONES_RESTAURANTE V
	ON R.IDRESTAURANTE = V.IDRESTAURANTE
	GROUP BY R.IDRESTAURANTE, R.NOMBRE, R.TELEFONO, R.CORREO,
	R.DIRECCION, R.IMAGEN, CR.NOMBRECATEGORIA
GO
INSERT [dbo].[RESTAURANTES] ([IDRESTAURANTE], [NOMBRE], [CORREO], [TELEFONO], [DIRECCION], [IMAGEN], [IDCATEGORIA]) VALUES (1, N'Pizza Posta', N'pizzaposta@gmail.com', N'915700738', N'Calle del Amparo, 81, 28012 Madrid, España', N'img1.jpeg', 11)
GO
INSERT [dbo].[RESTAURANTES] ([IDRESTAURANTE], [NOMBRE], [CORREO], [TELEFONO], [DIRECCION], [IMAGEN], [IDCATEGORIA]) VALUES (2, N'Chila', N'chilarestaurante@gmail.com', N'915302673', N'Calle De Silva 4, Madrid, Madrid 28013', N'img2.jpeg', 4)
GO
INSERT [dbo].[RESTAURANTES] ([IDRESTAURANTE], [NOMBRE], [CORREO], [TELEFONO], [DIRECCION], [IMAGEN], [IDCATEGORIA]) VALUES (3, N'Bells Cookie Co', N'bellscookie@gmail.com', N'699413217', N'Calle del Conde de Peñalver, 66, 28006 Madrid, España', N'img3.jpeg', 6)
GO
INSERT [dbo].[RESTAURANTES] ([IDRESTAURANTE], [NOMBRE], [CORREO], [TELEFONO], [DIRECCION], [IMAGEN], [IDCATEGORIA]) VALUES (4, N'Fridays', N'fridaysburgers@gmail.com', N'681390215', N'Paseo de La Habana, 17, 28036 Madrid, España', N'img4.jpeg', 1)
GO
INSERT [dbo].[RESTAURANTES] ([IDRESTAURANTE], [NOMBRE], [CORREO], [TELEFONO], [DIRECCION], [IMAGEN], [IDCATEGORIA]) VALUES (5, N'SANABOWLS', N'sanabowls@gmail.com', N'921732155', N'Calle de Vallehermoso, 42, 28015 Madrid, España', N'img5.jpeg', 14)
GO
INSERT [dbo].[RESTAURANTES] ([IDRESTAURANTE], [NOMBRE], [CORREO], [TELEFONO], [DIRECCION], [IMAGEN], [IDCATEGORIA]) VALUES (6, N'Nemrut Legazpi', N'kebabnemrut@gmail.com', N'687389301', N'Paseo del Molino, 1, 28045 Madrid, España', N'img6.jpeg', 3)
GO
INSERT [dbo].[RESTAURANTES] ([IDRESTAURANTE], [NOMBRE], [CORREO], [TELEFONO], [DIRECCION], [IMAGEN], [IDCATEGORIA]) VALUES (7, N'Mad Mad Vegan', N'madmadvegan@gmail.com', N'673291355', N'Calle de Lavapiés, 16, 28012 Madrid, España', N'img7.jpeg', 2)
GO
INSERT [dbo].[RESTAURANTES] ([IDRESTAURANTE], [NOMBRE], [CORREO], [TELEFONO], [DIRECCION], [IMAGEN], [IDCATEGORIA]) VALUES (8, N'Mayura', N'mayura@gmail.com', N'977532104', N'Paseo de los Melancólicos, 7, 28005 Madrid, España', N'img8.jpeg', 7)
GO
INSERT [dbo].[RESTAURANTES] ([IDRESTAURANTE], [NOMBRE], [CORREO], [TELEFONO], [DIRECCION], [IMAGEN], [IDCATEGORIA]) VALUES (9, N'Saboriz Sandwich', N'saboriz@gmail.com', N'934760241', N'Calle de Modesto Lafuente, 64, 28003 Madrid, España', N'img9.jpeg', 5)
GO
INSERT [dbo].[RESTAURANTES] ([IDRESTAURANTE], [NOMBRE], [CORREO], [TELEFONO], [DIRECCION], [IMAGEN], [IDCATEGORIA]) VALUES (10, N'Birrieria Dos Coyotes', N'doscoyotes@gmail.com', N'912834710', N'Calle de San Bernardo, 86, 28015 Madrid, España', N'img10.jpeg', 10)
GO
INSERT [dbo].[RESTAURANTES] ([IDRESTAURANTE], [NOMBRE], [CORREO], [TELEFONO], [DIRECCION], [IMAGEN], [IDCATEGORIA]) VALUES (11, N'Oven', N'overpasta@gmail.com', N'911552107', N'Calle de Fuencarral, 74, 28004 Madrid, España', N'img11.jpeg', 8)
GO
INSERT [dbo].[RESTAURANTES] ([IDRESTAURANTE], [NOMBRE], [CORREO], [TELEFONO], [DIRECCION], [IMAGEN], [IDCATEGORIA]) VALUES (12, N'Honest Greens', N'honestgreens@gmail.com', N'677482531', N'Calle de Fuencarral, 95, 28004 Madrid, España', N'img12.jpeg', 14)
GO
INSERT [dbo].[RESTAURANTES] ([IDRESTAURANTE], [NOMBRE], [CORREO], [TELEFONO], [DIRECCION], [IMAGEN], [IDCATEGORIA]) VALUES (13, N'CHUCKCHUCK CHICKEN', N'chuckchuck@gmail.com', N'989302135', N'Calle del Mesón de Paredes, 45, 28012 Madrid, España', N'img13.jpeg', 12)
GO
INSERT [dbo].[RESTAURANTES] ([IDRESTAURANTE], [NOMBRE], [CORREO], [TELEFONO], [DIRECCION], [IMAGEN], [IDCATEGORIA]) VALUES (14, N'Ninja Taberna', N'ninjataberna@gmail.com', N'943437890', N'Calle de la Princesa, 13, 28008 Madrid, EMEA, España', N'img14.jpeg', 9)
GO
INSERT [dbo].[RESTAURANTES] ([IDRESTAURANTE], [NOMBRE], [CORREO], [TELEFONO], [DIRECCION], [IMAGEN], [IDCATEGORIA]) VALUES (15, N'TEIKIT', N'teikit@gmail.com', N'987613000', N'Calle Imperial, 18, 28012 Madrid, España', N'img15.jpeg', 13)
GO
INSERT [dbo].[RESTAURANTES] ([IDRESTAURANTE], [NOMBRE], [CORREO], [TELEFONO], [DIRECCION], [IMAGEN], [IDCATEGORIA]) VALUES (16, N'Cinnabon', N'cinnabon@gmail.com', N'671224088', N'Cc Principe Pio, Paseo de la Florida, 2, 28008 Madrid, España', N'img16.jpeg', 6)
GO
INSERT [dbo].[RESTAURANTES] ([IDRESTAURANTE], [NOMBRE], [CORREO], [TELEFONO], [DIRECCION], [IMAGEN], [IDCATEGORIA]) VALUES (17, N'Skyrland', N'skyrland@gmail.com', N'922653313', N'Calle de Sandoval, 6, 28010 Madrid, España', N'img17.jpeg', 15)
GO
INSERT [dbo].[RESTAURANTES] ([IDRESTAURANTE], [NOMBRE], [CORREO], [TELEFONO], [DIRECCION], [IMAGEN], [IDCATEGORIA]) VALUES (18, N'Hattori Hanzo', N'hattorihanzo@gmail.com', N'673219073', N'Calle de Mesonero Romanos, 17, 28004 Madrid, España', N'img18.jpeg', 9)
GO
ALTER TABLE [dbo].[RESTAURANTES]  WITH CHECK ADD  CONSTRAINT [FK_RESTAURANTES_CATEGORIAS_RESTAURANTES] FOREIGN KEY([IDCATEGORIA])
REFERENCES [dbo].[CATEGORIAS_RESTAURANTES] ([IDCATEGORIA])
GO
ALTER TABLE [dbo].[RESTAURANTES] CHECK CONSTRAINT [FK_RESTAURANTES_CATEGORIAS_RESTAURANTES]
GO
